### ISSUE TITLE
bitcoind not compiled with zmq support

### ISSUE THREAD

**Issue by seth586** [freenas/iocage-plugin-bitcoin-node#2]
The build of bitcoind used in this plugin is not [compiled with zeromq support](https://github.com/bitcoin/bitcoin/blob/master/doc/zmq.md)

This is a [requirement](https://github.com/lightningnetwork/lnd/blob/master/docs/INSTALL.md) for `lnd` and possibly other bitcoin apps.

Suggest compiling with zeromq support by running a compile with `pkg libzmq4` installed.

ZeroMQ is compiled in by default on the 'official' binaries, if you want to call bitcoin.org 'official' :-)

See more on compiling on my guide [here](https://github.com/seth586/guides/blob/master/FreeNAS/freenas_2_bitcoin.md)

`libzmq4` is a build-time dependency and a run-time dependency, so this would also suggest the plugin have pkg `libzmq4` installed.

**Comment by MiwiDots** [comment]
Thank you for your feedback, you are right https://github.com/freebsd/freebsd-ports/blob/master/net-p2p/bitcoin-daemon/Makefile#L14 zeromq is per default off. I will enable it in the next package build.

- Martin

**Comment by seth586** [comment]
Excellent, thank you!

**Comment by MiwiDots** [comment]
Just saw it's also default on fbsd side now. So we can close that.
